### ISSUE TITLE
Adding route coordinates

### ISSUE THREAD

**Issue by gbprz** [wtg/shuttle_tracking_2#18]
We need to add a Google map to the "Routes" form under the admin pages where users can add markers and build a list of coordinates to create each route. These coordinates will then be used to draw a line on the fullscreen map for each route.

**Comment by kench** [comment]
Design questions to think about:

Should routes be exposed as a GeoJSON line?

Should there be a validation that ensures that stops should be a distinct point on the line?  For route arrival analysis/prediction, this allows clients to map stops->point on the route easier without resorting to fuzzy matching.

**Comment by gbprz** [comment]
f9b18744e0cafbb1a875e50f2972e0debdb92895
